using System.Text.Json.Serialization;
using GitlabMCP.Contracts.Deploy;

namespace GitlabMCP.Contracts.Serialization;

/// <summary>
///     Source-generated JSON metadata for every Deploy-domain payload record (runners, environments,
///     deployments, releases, deploy keys/tokens, pages domains, secure files, runner controllers) crossing
///     the MCP boundary.
///     ALL <c>[JsonSerializable]</c> attributes for this domain live in THIS ONE FILE, deliberately separate
///     from <see cref="GitlabMcpJsonContext" /> — see that file's header comment for the verified CS8785
///     generator bug that splitting a context's attribute-bearing files across two files triggers. Each
///     domain gets its own context class instead of appending to the shared Epics/Ping context.
/// </summary>
[JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Metadata)]
[JsonSerializable(typeof(ReleaseSummary))]
[JsonSerializable(typeof(ReleaseListResult))]
[JsonSerializable(typeof(RunnerSummary))]
[JsonSerializable(typeof(RunnerListResult))]
[JsonSerializable(typeof(RunnerControllerScopeSummary))]
[JsonSerializable(typeof(RunnerControllerScopeListResult))]
[JsonSerializable(typeof(RunnerControllerTokenSummary))]
[JsonSerializable(typeof(RunnerControllerTokenListResult))]
[JsonSerializable(typeof(RunnerJobSummary))]
[JsonSerializable(typeof(RunnerJobListResult))]
[JsonSerializable(typeof(RunnerManagerSummary))]
[JsonSerializable(typeof(RunnerManagerListResult))]
[JsonSerializable(typeof(RunnerProjectSummary))]
[JsonSerializable(typeof(RunnerProjectListResult))]
[JsonSerializable(typeof(RunnerTokenResetResult))]
[JsonSerializable(typeof(RunnerDeleteResult))]
[JsonSerializable(typeof(RunnerProjectUnassignResult))]
[JsonSerializable(typeof(RunnerControllerSummary))]
[JsonSerializable(typeof(RunnerControllerListResult))]
[JsonSerializable(typeof(RunnerControllerDeleteResult))]
[JsonSerializable(typeof(RunnerControllerScopeRemoveResult))]
[JsonSerializable(typeof(PagesDomainSummary))]
[JsonSerializable(typeof(PagesDomainListResult))]
[JsonSerializable(typeof(PagesDomainDetail))]
[JsonSerializable(typeof(PagesDeploymentSummary))]
[JsonSerializable(typeof(PagesSettingsSummary))]
[JsonSerializable(typeof(PagesUnpublishResult))]
[JsonSerializable(typeof(DeploymentMergeRequestSummary))]
[JsonSerializable(typeof(DeploymentMergeRequestListResult))]
[JsonSerializable(typeof(DeployKeySummary))]
[JsonSerializable(typeof(DeployKeyListResult))]
[JsonSerializable(typeof(DeployKeyDeleteResult))]
[JsonSerializable(typeof(DeployTokenSummary))]
[JsonSerializable(typeof(DeployTokenListResult))]
[JsonSerializable(typeof(DeployTokenCreated))]
[JsonSerializable(typeof(DeployTokenDeleteResult))]
[JsonSerializable(typeof(SecureFileSummary))]
[JsonSerializable(typeof(SecureFileListResult))]
[JsonSerializable(typeof(SecureFileDownload))]
[JsonSerializable(typeof(SecureFileDeleteResult))]
[JsonSerializable(typeof(EnvironmentSummary))]
[JsonSerializable(typeof(EnvironmentListResult))]
[JsonSerializable(typeof(EnvironmentDeleteResult))]
[JsonSerializable(typeof(StopStaleEnvironmentsResult))]
[JsonSerializable(typeof(ReviewAppDeletionResult))]
[JsonSerializable(typeof(DeploymentSummary))]
[JsonSerializable(typeof(DeploymentListResult))]
[JsonSerializable(typeof(DeploymentDetail))]
[JsonSerializable(typeof(DeploymentDeleteResult))]
[JsonSerializable(typeof(DeploymentApprovalSummary))]
[JsonSerializable(typeof(RunnerControllerTokenRevokeResult))]
[JsonSerializable(typeof(DeployAccessLevelSummary))]
[JsonSerializable(typeof(ApprovalRuleSummary))]
[JsonSerializable(typeof(ProtectedEnvironmentSummary))]
[JsonSerializable(typeof(ProtectedEnvironmentListResult))]
[JsonSerializable(typeof(EnvironmentUnprotectResult))]
[JsonSerializable(typeof(FreezePeriodSummary))]
[JsonSerializable(typeof(FreezePeriodListResult))]
[JsonSerializable(typeof(FreezePeriodDeleteResult))]
[JsonSerializable(typeof(ReleaseDeleteResult))]
[JsonSerializable(typeof(ReleaseEvidenceSummary))]
[JsonSerializable(typeof(GenerateReleaseEvidenceResult))]
[JsonSerializable(typeof(ReleaseLinkSummary))]
[JsonSerializable(typeof(ReleaseLinkListResult))]
[JsonSerializable(typeof(ReleaseLinkDeleteResult))]
[JsonSerializable(typeof(LatestReleaseSummary))]
[JsonSerializable(typeof(LatestReleaseAssetSummary))]
[JsonSerializable(typeof(LatestReleaseResult))]
[JsonSerializable(typeof(ReleaseAssetDownload))]
[JsonSerializable(typeof(PagesAccessResult))]
[JsonSerializable(typeof(ProjectPagesDomainListResult))]
[JsonSerializable(typeof(PagesDomainDeleteResult))]
public sealed partial class DeployJsonContext : JsonSerializerContext;